# Generated by Django 3.2.9 on 2021-11-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('experence', models.PositiveIntegerField()),
            ],
        ),
    ]
