# Generated by Django 3.2.9 on 2021-11-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='experence',
            new_name='experience',
        ),
    ]
